### ISSUE TITLE
Add license information in package.json

### ISSUE THREAD

**Issue by ihbar** [lutzer/node-red-contrib-finite-statemachine#10]
Hello

Could you add the license information in package.json ?
- It would be useful to have the license displayed in npm (if not defined, npm  shows License "none")
- Some build tool check the information and generates warning if information is not found.

Just need to add in package.json   "license": "MIT",

Thank you
Stephane

**Comment by lutzer** [comment]
done. thank you!

**Comment by ihbar** [comment]
Thanks a lot
