### ISSUE TITLE
FSM deletes all properties of msg

### ISSUE THREAD

**Issue by RSWilli** [lutzer/node-red-contrib-finite-statemachine#12]
I'm using the FSM for a light switch. I have an http entry that either sets the the light state or triggers a "test" transition, which is a loop on the current state, to get the state the machine is in (which would be a nice feature if this was a native feature btw :D).

My problem is, that since the FSM deletes the req and res properties on msg, I cannot send the resulting state back to the client.

Would it be possible, that payload and topic are changed, but the rest of the incoming msg object stays the same?

**Comment by lutzer** [comment]
hey. sorry for taking so long to respond to this. the current structure of the statemachine does not allow to forward the original message easily. maybe its possible in your case to save the original msg in a flow variable and merge it later on with the statemachine output?

**Comment by RSWilli** [comment]
yeah i am taking a different route by now. I looked at the code and figured that such a change would not be easy
