### ISSUE TITLE
Cannot edit FSM (Mac, Safari)

### ISSUE THREAD

**Issue by MartinJura** [lutzer/node-red-contrib-finite-statemachine#25]
I am using the FSM node for quite some time. Today I had the need to edit the FSM (states and conditions) and noticed that I can't open the editor.

I am running NodeRED 2.1.4. I am using Mac OS 12.1 (Monterey) and Safari (15.2). The "arrow down" and "three dots" don't respond to mouse clicks.

<img width="486" alt="CleanShot 2021-12-18 at 16 01 10@2x" src="https://user-images.githubusercontent.com/96344115/146645545-ec87bfc7-137b-4c7f-b4d7-526fd1195419.png">
.

**Comment by lutzer** [comment]
hey, thank you. it should be fixed with v2.1.2. Just published it.

**Comment by MartinJura** [comment]
Upgraded, tested and everything is working as expected! Thanks for your prompt response!
