### ISSUE TITLE
Cannot edit the fsm definition - on latest versions

### ISSUE THREAD

**Issue by dalethomas81** [lutzer/node-red-contrib-finite-statemachine#26]
I am running the latest version of node-red-contrib-finite-statemachine (2.1.2) as well as the latest version of node-red (2.1.4) and I am unable to edit the FSM definition.

When the definition is edited, the new definition will remain in the text box and the visualization of the FSM will render. However, after clicking done node-red does not register any changes and when the editing menu is reopened the definition is the reverted to the previous one (which is the default FSM definition)

I have never used this library before so I'm not sure if this is normal behavior. As a work around, I am editing my flow.json directly and that works just fine. It seems to just be a problem in the HTML scripting.

**Comment by dalethomas81** [comment]
One other note is that I did find a misspelling in the HTML script here. I corrected it and restarted node-red but that did not seem to have any effect.

        typeField: $("#ode-input-fsm-definition")

https://github.com/lutzer/node-red-contrib-finite-statemachine/blob/7d6d269882843ea98f58cdac286d2f1c11935992/src/finite-state-machine-node.html#L120

**Comment by lutzer** [comment]
thank you. that is a major bug. It should be fixed now with version 2.1.3. Please let me know if it works for you.

**Comment by dalethomas81** [comment]
That did it - thank you so much! I wish I could have contributed more to that so thank you for the work. This is a really nice piece of software. I really like the visual representation of the state machine.
