### ISSUE TITLE
Syntax error of v1.0.2 in Homematic (RaspberryMatic) and Node-RED (RedMatic)

### ISSUE THREAD

**Issue by StephanStS** [lutzer/node-red-contrib-finite-statemachine#8]
If used in a Homematic environment (including RedMatic), the node cannot be loaded.
The manage palette dialog shows:

![2020-05-04 13_24_45-Clipboard](https://user-images.githubusercontent.com/57687516/80961184-ae1a5580-8e0a-11ea-9526-20f7a000830b.png)

The older version 0.2.11 ran without problems.
This can be seen on a 100% fresh Homematic/RedMatic installation as well as on another system (RPi) running an active Homematic instance with running programs etc. at home.
RedMatic contains Node-RED v1.0.5. 

What shall I investigate as a next step?
The 100% clean installation I only set up for investigation purposes, so any crashing tests are no problem. :-) 
The installation log within RedMatic shows: 
_-----------------------------------------------------------
2020-05-04T14:54:56.510Z Install : node-red-contrib-finite-statemachine 1.0.2

2020-05-04T14:54:57.712Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-finite-statemachine@1.0.2
2020-05-04T14:55:09.618Z [err] npm
2020-05-04T14:55:09.619Z [err]  WARN node-red-project@0.0.1 No repository field.
2020-05-04T14:55:09.619Z [err] npm WARN node-red-project@0.0.1 No license field.
2020-05-04T14:55:09.620Z [err] 
2020-05-04T14:55:09.625Z [out] + node-red-contrib-finite-statemachine@1.0.2
2020-05-04T14:55:09.625Z [out] added 5 packages from 11 contributors in 9.419s
2020-05-04T14:55:09.899Z rc=0_

**Comment by lutzer** [comment]
im trying to reproduce that error. could you tell me what node.js version is running on the system?

**Comment by StephanStS** [comment]
node --version shows v12.16.1 on the homematic system.
On a system where it runs there is v12.16.3 installed.

**Comment by lutzer** [comment]
i just installed a fresh homematic system on a raspberry pi 2 model b (RaspberryMatic-3.51.6.20200420-rpi3) with redmatic (redmatic-5.5.3). it is running node v12.16.1 and node-red v1.0.5. The statemachine installs without problems. 

It also installs on os x running node.js v12.16.3. Gonna do some further tests to find the error. What is your operating system? is node-red running in a docker container by any chance?

**Comment by lutzer** [comment]
I just released a new version (v1.03) now which might have fixed the bug. it should be available over the package manager in a few hours. Let me know if it solved the problem.

**Comment by StephanStS** [comment]
Jep. Perfect, it works and node is functioning as desired.

![grafik](https://user-images.githubusercontent.com/57687516/81722109-36d76800-9481-11ea-97fa-e1b469e89650.png)

Tested on three different Node-RED instances: 2 x Homematic/RedMatic, 1 x DietPi.
