### ISSUE TITLE
After upgrading to version 1.0.2 message  missing node types occures

### ISSUE THREAD

**Issue by roupec** [lutzer/node-red-contrib-finite-statemachine#9]
Flows stopped due to missing node types.

finite-state-machine

**Comment by roupec** [comment]
During installation:

9 May 15:51:21 - [info] Uninstalling module: node-red-contrib-finite-statemachine
9 May 15:51:24 - [info] Uninstalled module: node-red-contrib-finite-statemachine
9 May 15:51:24 - [info] Removed node types:
9 May 15:51:24 - [info]  - node-red-contrib-finite-statemachine:finite-state-machine
9 May 15:52:50 - [info] Installing module: node-red-contrib-finite-statemachine, version: 1.0.2
9 May 15:52:54 - [info] Installed module: node-red-contrib-finite-statemachine
9 May 15:52:54 - [info] Added node types:
9 May 15:52:54 - [info]  - node-red-contrib-finite-statemachine:finite-state-machine : SyntaxError: Unexpected token = (line:1)
9 May 15:54:28 - [info] Stopping modified flows
9 May 15:54:28 - [info] Stopped modified flows
9 May 15:54:28 - [info] Waiting for missing types to be registered:
9 May 15:54:28 - [info]  - finite-state-machine
9 May 15:55:43 - [info] Stopping modified flows

**Comment by lutzer** [comment]
i am trying to reproduce your error. what system is your node red instance running on? what node red version are you using?

what you could try: manually delete the node-red-contrib-finite-statemachine folder in your .node-red/node_modules folder: `rm -rf ~/.node-red/node_modules/node-red-contrib-finite-statemachine/`. then install it again through the palette manager.

**Comment by lutzer** [comment]
could you also tell me what version of node.js is running on your system?

**Comment by lutzer** [comment]
v1.0.3 should fix this bug. if it doesnt, let me know.

**Comment by StephanStS** [comment]
@roupec: Hello Petr,
is the above issue fixed? If yes, you could please close it.
